"""empty message

Revision ID: 2bfd6c26f1f2
Revises: 7e517c533026
Create Date: 2018-11-24 19:53:32.735998

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2bfd6c26f1f2'
down_revision = '7e517c533026'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('video',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('angriness_level', sa.Float(precision=8), nullable=True),
    sa.Column('happiness_level', sa.Float(precision=8), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_video_timestamp'), 'video', ['timestamp'], unique=False)
    op.drop_index('ix_emotion_timestamp', table_name='emotion')
    op.drop_table('emotion')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('emotion',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('client_id', sa.INTEGER(), nullable=False),
    sa.Column('timestamp', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_emotion_timestamp', 'emotion', ['timestamp'], unique=False)
    op.drop_index(op.f('ix_video_timestamp'), table_name='video')
    op.drop_table('video')
    # ### end Alembic commands ###
