"""empty message

Revision ID: 7e517c533026
Revises: ea262d1712ca
Create Date: 2018-11-24 14:53:17.702361

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7e517c533026'
down_revision = 'ea262d1712ca'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('message', sa.Column('text', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('message', 'text')
    # ### end Alembic commands ###
