"""empty message

Revision ID: c9459da70fca
Revises: dd4fcf7225a0
Create Date: 2018-11-24 13:37:06.954239

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c9459da70fca'
down_revision = 'dd4fcf7225a0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('emotion', sa.Column('text', sa.Text(), nullable=False))
    op.add_column('emotion', sa.Column('timestamp', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_emotion_timestamp'), 'emotion', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_emotion_timestamp'), table_name='emotion')
    op.drop_column('emotion', 'timestamp')
    op.drop_column('emotion', 'text')
    # ### end Alembic commands ###
