"""empty message

Revision ID: ea262d1712ca
Revises: b8f9a1c5dbe6
Create Date: 2018-11-24 14:42:39.842865

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ea262d1712ca'
down_revision = 'b8f9a1c5dbe6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('message', sa.Column('polarity', sa.Numeric(precision=8, asdecimal=False), nullable=True))
    op.add_column('message', sa.Column('subjectivity', sa.Numeric(precision=8, asdecimal=False), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('message', 'subjectivity')
    op.drop_column('message', 'polarity')
    # ### end Alembic commands ###
